### ISSUE TITLE
 XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by michaelngangom** [paulmillr/fetch-streaming#1]
Hi Paul,
I am trying to use the package but, when I try to run fetch, I get the below error:
(node:454) UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined

Do you know what I could be missing here?

**Comment by paulmillr** [comment]
Hi. The package is for browser only. Not for nodejs.

**Comment by michaelngangom** [comment]
Thanks @paulmillr
